##### 

IMU:
  # Default:9.81; gravity in the place your robot deployed
  gravity: 9.81               

  # Note: Noise density (continuous-time) from dataset from kalibr_allen
  # Default: 1.926e-04 from datasheet
  accelerometer_noise_density: 2.0000e-3

  # Note: Bias random walk from kalibr_allen
  accelerometer_random_walk: 3.0000e-3

  # Note: Noise density (continuous-time) from kalibr_allen
  # Default: 8.7e-05 from datasheet
  gyroscope_noise_density: 1.6968e-04

  # Note: Bias random walk from kalibr_allen
  gyroscope_random_walk: 1.9393e-05
        
DVL:
  # imu is reference frame
  T_I_D: 
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
  # Default:0.0; Time offset from Temporal calibrtion between DVL and IMU: (t_imu = t_dvl + t_offset)
  # TODO: this value will be overide by IMU-DVL alignment
  timeoffset_I_D: 0.0         
  # Default:1.0; Scale factor for DVL measurement effected by sound speed (caused by salinity, temperature...)
  scale: 1.0
  # white noise on DVL tottom track 3-axis velocity measurement
  bt_v_noise: [0.005, 0.005, 0.005]