##### System Parameters #####
SYS:
  # Default: 20; 
  # Note: frequency for backend processing(MSCKF update), increase if more data need for processing ( keep it as camera fequency)
  backend_hz: 30
  # Note: 0: pressure from DVL BT; 1: pressure from individual source (pressure from CP)
  # pressure from BT and CP, only use one. since pressure from CP will has IMU propagation, from BT only simple update
  pressure_source: 1
  # DVL mount angle:
  


INIT:
  # Default: 1; (0: static; 1:DVL-aided; 2:SFM-aided)
  # Note: Estimate IMU bias and find out the rotation matrix between inertial world frame and IMU body frame;
  imu_init_mode: 1      

  # Default: 10
  # Note: how many IMU data is selected to detect IMU jump (suddenly move)  
  imu_window: 10

  # Default: 0.2
  # Note: the IMU variance threshold that indicates IMU jump inclued
  imu_var: 0.2

  # Default: 0.07
  # Note: IMU accleraion difference in x-axis(forward direction) shows at the suddenly movement time
  imu_delta: 0.07

  # Default: 5
  # Note: how many DVL data is selected to detect DVL jump (suddenly move)  
  dvl_window: 4
  
  # Default: 0.05
  # Note: DVL velocity difference in x-axis(forward direction) shows at the suddenly movement time
  dvl_delta: 0.05

  # use the given initialized state or not
  init_state_given: false

  # example: t, qx,qy,qz,qw, px,py,pz, vx,vy,vz, bgx,bgy,bgz, bax,bay,baz
  init_state: [0, 0,0,0,0, 0,0,0, 0,0,0, 0,0,0, 0,0,0]
  
#### MSCKF parameters
MSCKF:
  # enable DVL exterisic rotation calibration 
  dvl_exterisic_R: false
  # enable DVL exterisic translation calibration 
  dvl_exterisic_p: false
  # enable DVL time offset calibration
  dvl_timeoffset: false
  # enable DVL scale calibration
  dvl_scale: false
  # Max clone storage for DVL
  dvl_clone: 0 
