#### Camera feature tracking parameters

# option: TRACK_FEATURE, TRACK_KLT, TRACK_DESCRIPTOR
# FRONT_END:
TRACK:
  mode: TRACK_NONE
  num_aruco: 1024
  downsize_aruco: false
  use_stereo: false
  max_camera: 1
  cam_id: 0
  downsample_ratio: 0.5
  # 0: Histogram equalization; 1: contrast limited adaptive histogram equalization (CLAHE) 
  img_enhancement: 1