##################################################################################### 
#####                                  IMU                                      #####
##################################################################################### 
IMU:
  # Default:9.81; gravity in the place your robot deployed, e.g. GLRC
  gravity: 9.81               

  # Note: Noise density (continuous-time) from dataset from kalibr_allen
  accelerometer_noise_density: 2.0000e-3

  # Note: Bias random walk from kalibr_allen
  accelerometer_random_walk: 3.0000e-3

  # Note: Noise density (continuous-time) from kalibr_allen
  gyroscope_noise_density: 1.6968e-04

  # Note: Bias random walk from kalibr_allen
  gyroscope_random_walk: 1.9393e-05


##################################################################################### 
#####                                 CAM0                                      #####
##################################################################################### 
CAM0:
  T_C_I:
  - [0.01486554,  0.99955725, -0.02577444,  0.06522291]
  - [-0.99988093,  0.01496721,  0.00375619, -0.02070639]
  - [0.0041403 ,  0.02571553,  0.99966073, -0.0080546]
  - [0.0,        0.0,          0.0,        1.0]
  # radial-tangential[k1,k2,r1,r2]
  distortion_coeffs: [-0.28340811, 0.07395907, 0.00019359, 1.76187114e-05]
  # f_x, f_y, c_x, c_y
  intrinsics: [458.654, 457.296, 367.215, 248.375]  
  # this parameter not loaded
  resolution: [752, 480]
  camera_model: pinhole
  distortion_model: radtan
  timeoffset_C_I: 0
  # unit in pixel
  # noise: 0.035  
  noise: 0.02  
  # noise: 0.01  