####################################################################################
############################     System Parameters   ##########################
####################################################################################

SYS:
  # Default: ; 
  # Note: frequency for backend processing(MSCKF update), increase if more data need for processing 
  backend_hz: 100
  # sensors will be fused
  sensors: [IMU, CAM0]
  # rostopics used for each sensor
  topics: 
    - {IMU: /imu0}
    - {CAM0: /cam0/image_raw}
  # data storage 
  buffers:
    - {CAM0: 10}

####################################################################################
############################    MSCKF estimation setup    ##########################
####################################################################################

MSCKF:

  ################################    Camera    ##################################

  # enable camera exterisic rotation calibration 
  cam_exterisic_R: false
  # enable camera exterisic translation calibration 
  cam_exterisic_p: false
  # enable camera time offset calibration
  cam_timeoffset: false
  # Max camera clone
  cam_clone: 20

  ################################    Update    ##################################

  # Index of clone need to marginalize 
  # example: we have 10 clones [0,1,2,3,4,5,6,7,8,9]
  #          the marg clone measurements: oldest, second latest [0,8]
  # marg_meas_index: [0, 18]
  marg_meas_index: [-1]
  
  # brief: marginalized pose at slide-windows index (or clone state index)
  # note: this select from 'marg_meas_index', no need exactly same as 'marg_meas_index'
  marg_pose_index: [-1]

  # in open_vins(40), but it's occasionally update at 40
  # but here, tracking will stop so always update as 40
  max_msckf_update: 20

  # max line of residual lines for update, maybe used for futures
  # max_update_lines: 1500 