##################################################################################### 
#####                                  IMU                                      #####
##################################################################################### 
IMU:
  # Default:9.81; 
  # gravity in the place your robot deployed
  gravity: 9.80733               

  # Note: Noise density (continuous-time) from dataset from kalibr_allen
  # Default: 1.926e-04 from datasheet
  accelerometer_noise_density: 4.2e-04

  # Note: Bias random walk from kalibr_allen
  accelerometer_random_walk: 2.857e-05

  # Note: Noise density (continuous-time) from kalibr_allen
  # Default: 8.7e-05 from datasheet
  gyroscope_noise_density: 8.014e-05

  # Note: Bias random walk from kalibr_allen
  gyroscope_random_walk: 0.534e-05

##################################################################################### 
#####                                  DVL                                      #####
##################################################################################### 
DVL:
  # imu is reference frame
  T_I_D: 
  - [  -0.999928,   0.0116206, -0.00288846,   0.433828]
  - [  0.0115923,    0.999886,  0.00962664,   0.086180]
  - [      0.003,  0.00959246,   -0.999949,  -0.302024]
  - [        0.0,         0.0,         0.0,        1.0]
  # Default:0.0; Time offset from Temporal calibrtion between DVL and IMU: (t_imu = t_dvl + t_offset)
  # TODO: this value will be overide by IMU-DVL alignment
  timeoffset_I_D: 0.0         
  # Default:1.0; Scale factor for DVL measurement effected by sound speed (caused by salinity, temperature...)
  scale: 0.944666667
  # noise on DVL tottom track 3-axis velocity measurement
  # noise_bt: [0.1, 0.15, 0.2]
  # noise_bt: [0.05, 0.1, 0.15]
  noise_bt: [0.1, 0.1, 0.1]
  

##################################################################################### 
#####                               Pressure                                    #####
##################################################################################### 
PRESSURE:
  # Note: the angle that the actual mounting position rotate to the standing position,
  #       used to transfer pressure measurement into DVL frame's Z
  # Default: 0: x-forward, up-looking; PI: x-forward, down-looking; -PI/2: x-forward, right-looking; PI/2: x-forward, left-looking
  mount_angle: 0
  # noise for pressure update
  # default: 0.01
  noise_pressure: 0.01
