####################################################################################
############################     System Parameters   ##########################
####################################################################################

SYS:
  # Default: 20; 
  # Note: frequency for backend processing(MSCKF update), increase if more data need for processing ( keep it as camera fequency)
  backend_hz: 30
  # sensors will be fused
  sensors: [IMU, DVL, PRESSURE]
  # rostopics used for each sensor
  topics: 
    - {IMU: /rov/sensors/ahrs/imu/data}
    - {DVL: /rov/sensors/dvl/buttom_track_velocity}
    - {PRESSURE: /rov/sensors/dvl/pressure}

  buffers:
    # DVL cloud buffer to store how many seconds
    - {DVL_CLOUD: 10}

####################################################################################
############################    MSCKF estimation setup    ##########################
####################################################################################

#### MSCKF parameters
MSCKF:

  ##################################    DVL    ###################################

  # enable DVL exterisic rotation calibration 
  dvl_exterisic_R: false
  # enable DVL exterisic translation calibration 
  dvl_exterisic_p: false
  # enable DVL time offset calibration
  dvl_timeoffset: false
  # enable DVL scale calibration
  dvl_scale: false