##### System Parameters #####
SYS:
  # Default: 20; 
  # Note: frequency for backend processing(MSCKF update), increase if more data need for processing ( keep it as camera fequency)
  backend_hz: 30
  # Default: 2.0
  # Note: use this simply filter bad DVL velocity measurement
  dvl_v_threshold: 2.0 
  
#### MSCKF parameters
MSCKF:
  # enable DVL exterisic rotation calibration 
  dvl_exterisic_R: false
  # enable DVL exterisic translation calibration 
  dvl_exterisic_p: false
  # enable DVL time offset calibration
  dvl_timeoffset: false
  # enable DVL scale calibration
  dvl_scale: false
  # Max clone storage for DVL
  dvl_clone: 0 
