############################################
#### Camera feature tracking parameters ####
############################################

# option: TRACK_FEATURE, TRACK_KLT, TRACK_DESCRIPTOR
TRACK:
  mode: TRACK_KLT
  num_aruco: 1024
  downsize_aruco: false
  use_stereo: false
  max_camera: 1
  cam_id: 0
  downsample_ratio: 1.0
  # 0: Histogram equalization; 1: contrast limited adaptive histogram equalization (CLAHE) 
  img_enhancement: 1

# TRACK_FEATURE:
#   todo: 1

TRACK_KLT:
  num_pts: 250
  fast_threshold: 15
  grid_x: 5
  grid_y: 3
  min_px_dist: 8
  pyram: 3


############################################
#### Camera feature triangulation parameters ####
############################################
Feature:
  # Max condition number of linear triangulation matrix accept triangulated features
  max_cond_number: 10000
  # Minimum distance to accept triangulated features
  min_dist: 0.1
  # Minimum distance to accept triangulated features
  max_dist: 60
  # Multiplier to increase/decrease lambda
  lam_mult: 10 
  # Init lambda for Levenberg-Marquardt optimization
  init_lamda: 0.001  
  # Max runs for Levenberg-Marquardt
  max_runs: 5
  # Max lambda for Levenberg-Marquardt optimization
  max_lamda: 1e10
  # Cutoff for dx increment to consider as converged
  min_dx: 1e-6
  # Cutoff for cost decrement to consider as converged
  min_dcost: 1e-6
  # Max baseline ratio to accept triangulated features
  max_baseline: 40


############################################
####        Keyframe Strategy           ####
############################################
Keyframe:
  # option 1: frame count
  frame_count: 0 
  # option 2: relative motion constraint
  frame_motion: 0.0
  # 2: 2D space constraint, for up-looking ice surface, 3: 3D space constraint
  motion_space: 3
  # option 3: minimum tracked features
  min_tracked: 50
  # option 4: ratio = tracked features from last keyframe / total features at current frame
  scene_ratio: 1.0