####################################################################################
############################     System Parameters   ##########################
####################################################################################

SYS:
  # Default: ; 
  # Note: frequency for backend processing(MSCKF update), increase if more data need for processing 
  backend_hz: 100
  # sensors will be fused
  # sensors: [IMU, DVL, PRESSURE, CAM0]
  sensors: [IMU, DVL, PRESSURE, CAM0, DVL_CLOUD]
  # sensors: [IMU, DVL, PRESSURE]
  # sensors: [IMU, CAM0]

  # rostopics used for each sensor
  topics: 
    - {IMU: /rov/sensors/ahrs/imu/data}
    - {DVL: /rov/sensors/dvl/bottom_track_velocity}
    - {PRESSURE: /rov/sensors/dvl/pressure}
    - {CAM0: /rov_remote/sensors/stereo/left/image_decompressed}
    - {DVL_CLOUD: /rov/sensors/dvl/pointcloud}

  buffers:
    # DVL cloud buffer to store how many seconds
    - {DVL_CLOUD: 10}


####################################################################################
############################    MSCKF estimation setup    ##########################
####################################################################################

MSCKF:
  ##################################    DVL    ###################################

  # enable DVL exterisic rotation calibration 
  dvl_exterisic_R: false
  # enable DVL exterisic translation calibration 
  dvl_exterisic_p: false
  # enable DVL time offset calibration
  dvl_timeoffset: false
  # enable DVL scale calibration
  dvl_scale: false

  ################################    Camera    ##################################

  # enable camera exterisic rotation calibration 
  cam_exterisic_R: false
  # enable camera exterisic translation calibration 
  cam_exterisic_p: false
  # enable camera time offset calibration
  cam_timeoffset: false
  # Max camera clone
  # default: 11 for non-key-frame
  cam_clone: 15 

  ################################    Update    ##################################
  
  # brief: marginalized measurements at slide-windows index (or clone state index)
  # example 1: we have 10 clones [0,1,2,3,4,5,6,7,8,9]
  #          the marg measurements: oldest, second latest [0,8]
  # example 2: [-1] means all     
  marg_meas_index: [0, 13]
  # marg_meas_index: [-1]

  # brief: marginalized pose at slide-windows index (or clone state index)
  # note: this select from 'marg_meas_index', no need exactly same as 'marg_meas_index'
  marg_pose_index: [0]

  # in open_vins(40), but it's occasionally update at 40
  # but here, tracking will stop so always update as 40
  # max_msckf_update: 20

  # max line of residual lines for update, maybe used for futures
  # max_update_lines: 1500 
