##################################################################################### 
#####                                  IMU                                      #####
##################################################################################### 
IMU:
  # Default:9.81; 
  # gravity in the place your robot deployed
  # The North Alaska from E. Thiel et al. GRAVITY MEASUREMENTS IN ALASKA
  gravity: 9.81               

  # Note: Noise density (continuous-time) from dataset from kalibr_allen
  # Default: 1.926e-04 from datasheet
  accelerometer_noise_density: 0

  # Note: Bias random walk from kalibr_allen
  accelerometer_random_walk: 0

  # Note: Noise density (continuous-time) from kalibr_allen
  # Default: 8.7e-05 from datasheet
  gyroscope_noise_density: 0

  # Note: Bias random walk from kalibr_allen
  gyroscope_random_walk: 0

##################################################################################### 
#####                                  DVL                                      #####
##################################################################################### 
DVL:
  # imu is reference frame
  T_I_D: 
  - [  1.0,  0.0,  0.0,  0.0]
  - [  0.0,  1.0,  0.0,  0.0]
  - [  0.0,  0.0,  1.0,  0.0]
  - [  0.0,  0.0,  0.0,  1.000]
  # Note: Time offset from Temporal calibrtion between DVL and IMU: (t_imu = t_dvl + t_offset)
  # TODO: this value will be overide by IMU-DVL alignment
  timeoffset_I_D: 0.0         
  # Default:1.0; Scale factor for DVL measurement effected by sound speed (caused by salinity, temperature...)
  scale: 1.0
  # noise on DVL tottom track 3-axis velocity measurement
  noise_bt: [0.1, 0.1, 0.1]
  

##################################################################################### 
##################################################################################### 

## Secondary camera
# CAM0:
#   # TODO: this tf should be not as same as GLRC, take a look at the calibration
#   T_C_I:
#   - [ 0.007862367268,  0.999953212142,  0.005635309016, -0.123220672745]
#   - [ 0.999968129426, -0.007854419126, -0.001431164675, -0.310185995908]
#   - [-0.00138683563,   0.005646381758, -0.999983097387, -0.278121515480]
#   - [ 0.000000000000,  0.000000000000,  0.000000000000,  1.000000000000]

#   # radial-tangential[k1,k2,r1,r2]
#   distortion_coeffs: [-0.229971614369661,0.173683036312323,-7.457584765784308e-04,0.002259672821916]
#   # f_x, f_y, c_x, c_y
#   intrinsics: [1845.542490218492,1846.046949112978, 825.6913274592704,605.8504151895138]  
#   resolution: [1616, 1240]
#   camera_model: pinhole
#   distortion_model: radtan
#   # Default: -0.0558 from IO-SYNC time difference
#   timeoffset_I_C: 0

##################################################################################### 
##################################################################################### 

## Primary camera
# CAM1:

