##################################################################################### 
#####                                  IMU                                      #####
##################################################################################### 
IMU:
  # Default:9.81; 
  # gravity in the place your robot deployed
  # The North Alaska from E. Thiel et al. GRAVITY MEASUREMENTS IN ALASKA
  gravity: 9.81               

  # Note: Noise density (continuous-time) from dataset from kalibr_allen
  # Default: 1.926e-04 from datasheet
  accelerometer_noise_density: 2.0000e-3

  # Note: Bias random walk from kalibr_allen
  accelerometer_random_walk: 3.0000e-3

  # Note: Noise density (continuous-time) from kalibr_allen
  # Default: 8.7e-05 from datasheet
  gyroscope_noise_density: 1.6968e-04

  # Note: Bias random walk from kalibr_allen
  gyroscope_random_walk: 1.9393e-05

##################################################################################### 
#####                                  DVL                                      #####
##################################################################################### 
DVL:
  # imu is reference frame
  T_I_D: 
  - [  1.0,  0.0,  0.0,  0.0]
  - [  0.0,  1.0,  0.0,  0.0]
  - [  0.0,  0.0,  1.0,  0.0]
  - [  0.0,  0.0,  0.0,  1.0]
  # Note: Time offset from Temporal calibrtion between DVL and IMU: (t_imu = t_dvl + t_offset)
  # TODO: this value will be overide by IMU-DVL alignment
  timeoffset_I_D: 0.0         
  # Default:1.0; Scale factor for DVL measurement effected by sound speed (caused by salinity, temperature...)
  scale: 1.0
  # noise on DVL tottom track 3-axis velocity measurement
  noise_bt: [0.1, 0.1, 0.1]
  

##################################################################################### 
##################################################################################### 

CAM0:
  T_C_I:
  - [ 0.0, 1.0,  0.0,  0.0]
  - [-1.0, 0.0,  0.0, -0.05]
  - [ 0.0, 0.0,  1.0,  0.0]
  - [ 0.0, 0.0,  0.0,  1.0]
  # radial-tangential[k1,k2,r1,r2]
  distortion_coeffs: [-0.28340811,0.07395907,0.00019359,1.76187114e-05]
  # f_x, f_y, c_x, c_y
  intrinsics: [458.654,457.296,367.215,248.375]  
  resolution: [752,480]
  timeoffset_I_C: 0
  # unit in pixel
  noise: 1
  camera_model: pinhole
  distortion_model: radtan

##################################################################################### 
##################################################################################### 

# CAM1:

