####################################################################################
############################     System Parameters   ##########################
####################################################################################

SYS:
  # Default: 20; 
  # Note: frequency for backend processing(MSCKF update), increase if more data need for processing ( keep it as camera fequency)
  backend_hz: 100
  # sensors will be fused
  # sensors: [IMU, DVL]
  sensors: [IMU, CAM0_FEATURE]
  # rostopics used for each sensor
  topics: 
    - {IMU: /ov_msckf/imu_sim}
    # - {DVL: /ov_msckf/dvl_sim}
    - {CAM0_FEATURE: /ov_msckf/feature_sim}
  # load some test files
  # csv: /home/lin/develop/data/sim/udel_gore/sim_NoCalibNoise_4_feat_position.txt
  buffers:
    # buffer to store how many seconds
    - {CAM0_FEATURE: 10}

####################################################################################
############################    MSCKF estimation setup    ##########################
####################################################################################

#### MSCKF parameters
MSCKF:

  ##################################    DVL    ###################################

  # enable DVL exterisic rotation calibration 
  dvl_exterisic_R: false
  # enable DVL exterisic translation calibration 
  dvl_exterisic_p: false
  # enable DVL time offset calibration
  dvl_timeoffset: false
  # enable DVL scale calibration
  dvl_scale: false


  ################################    Camera    ##################################

  ## enable camera exterisic rotation calibration 
  cam_exterisic_R: false
  ## enable camera exterisic translation calibration 
  cam_exterisic_p: false
  ## enable camera time offset calibration
  cam_timeoffset: false
  ## Max camera clone
  ## default: 11 for non-key-frame
  cam_clone: 12 

  ################################    Update    ##################################

  ## Index of clone need to marginalize 
  ## Option 1: we have 10 clones [0,1,2,3,4,5,6,7,8,9]
  ##          the marg clone measurements: oldest, second latest [0,8]
  ## Option 2: [-1] means use all 
  # marg_meas_index: [-1] 
  # marg_meas_index: [0, 10]
  marg_meas_index: [1, 10]
  
  # brief: marginalized pose at slide-windows index (or clone state index)
  # note: this select from 'marg_meas_index', no need exactly same as 'marg_meas_index'
  # example: [-1] means use first index from 'marg_meas_index'
  # marg_pose_index: [-1]
  # marg_pose_index: [0, 10]
  marg_pose_index: [1, 10]

  ## in open_vins(40), but it's occasionally update at 40
  ## but here, tracking will stop so always update as 40
  # max_msckf_update: 20

  # ## max line of residual lines for update, maybe used for futures
  # # max_update_lines: 1500 

  ################################    Marginalization    ##################################
