###############################################################################
###################    System Initailization Configuration    #################
###############################################################################

# This is the parameter must given
# Options: INIT_SETTING, INIT_STATIC, INIT_DVL_PRESSURE, INIT_CAMERA, INIT_DVL_CAMERA
# the given MODE shoud match to setting below
INIT_MODE: INIT_SETTING


###############################################################################
INIT_SETTING:
  # # Example:
  # SENSOR:
  #   # the timestamp that this sensor initialized
  #   time: 1614971124.344753027
  #   # initialized timeoffset 
  #   temporal: [0.01]
  #   #       q_x  q_y  q_z  q_w   x    y    z   v_x  v_y  v_z  bg_x  bg_y  bg_z  ba_x  ba_y  ba_z
  #   state: [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
  #   # initialized static transfomration between IMU and this sensor 
  #   extrinsic: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
  #   # initialized intrinsic parameters for this sensor: the size depend on sensors. e.g. scale for DVL; intrinsics for camera ... 
  #   intrinsic: [1.0, 2.0, 3.0]
  #   # initialized global transfomration for this sensor: Pressure, Magnetometer, GPS and so on may have this 
  #   global: [1.0, 2.0, 3.0, 0.0, 0.0, 0.0, 1.0]

  IMU:
    time: 1614971124.344753027
    # brief: orientation in quaterion form
    state: [-0.998573, 0.000816, 0.015993, 0.050947, 
                0.0000, 0.0000, 0.0000, 
               -0.346171, 0.008464, 0.042122, 
               -0.001849, -0.001689, -0.002033, 
              #  0.001, 0.001, -0.001, 
               -0.003053, -0.004853, -0.020769] 