###############################################################################
###################    System Initailization Configuration    #################
###############################################################################

# This is the parameter must given
# Options: INIT_SETTING, INIT_STATIC, INIT_DVL_PRESSURE, INIT_CAMERA, INIT_DVL_CAMERA
# the given MODE shoud match to setting below
INIT_MODE: INIT_SETTING


###############################################################################
INIT_SETTING:
  # # Example:
  # SENSOR:
  #   # the timestamp that this sensor initialized
  #   time: 1614971124.344753027
  #   # initialized timeoffset 
  #   temporal: [0.01]
  #   #       q_x  q_y  q_z  q_w   x    y    z   v_x  v_y  v_z  bg_x  bg_y  bg_z  ba_x  ba_y  ba_z
  #   state: [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
  #   # initialized static transfomration between IMU and this sensor 
  #   extrinsic: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
  #   # initialized intrinsic parameters for this sensor: the size depend on sensors. e.g. scale for DVL; intrinsics for camera ... 
  #   intrinsic: [1.0, 2.0, 3.0]
  #   # initialized global transfomration for this sensor: Pressure, Magnetometer, GPS and so on may have this 
  #   global: [1.0, 2.0, 3.0, 0.0, 0.0, 0.0, 1.0]

  IMU:
    time: 1648667257.549000025
    # brief: orientation in quaterion form
    state: [ -0.998042,-0.000759,-0.061302,0.012362, 
              0.0000, 0.0000, 0.0000, 
             -0.047861,-0.006861,-0.026561, 
             -0.007398,-0.001765,-0.022810, 
             -0.000676,-0.000716,-0.009552] 

  DVL:
    time: 1648667257.677178383
    # the timeoffset should not large like this ?
    temporal: [-0.124145746]

  PRESSURE:
    time: 1648667257.677178383
    global: [3.908000]   
 

###############################################################################
# INIT_STATIC:
  # todo: 0.0

###############################################################################
INIT_DVL_PRESSURE:
  # Default: 100hz IMU -> 10; 200hz IMU -> 20
  # TODO: replace with imu_time_duration: 0.1s
  # Note: how many IMU data is selected to detect IMU jump (suddenly move)  
  imu_window: 20

  # Default: 0.2
  # Note: the IMU variance threshold that indicates IMU jump inclued
  imu_var: 0.15

  # Default: 0.07
  # Note: IMU accleraion difference in x-axis(forward direction) shows at the suddenly movement time
  imu_delta: 0.2

  # Default: 5
  # Note: how many DVL data is selected to detect DVL jump (suddenly move)  
  dvl_window: 4
  
  # Default: 0.05
  # Note: DVL velocity difference in x-axis(forward direction) shows at the suddenly movement time
  dvl_delta: 0.05

  # Default: 1s
  #Note: how many second selected for initialization
  dvl_init_duration: 2


###############################################################################
# INIT_CAMERA:
  # todo: 0.0


###############################################################################
# INIT_DVL_CAMERA:
  # todo: 0.0
