############################################
#### Camera feature tracking parameters ####
############################################

KLT:
  num_aruco: 1024
  num_pts: 200
  fast_threshold: 15
  grid_x: 5
  grid_y: 3
  min_px_dist: 8
  downsize_aruco: false
  use_stereo: false
  max_camera: 2
  pyram: 3
  cam_id: 0
  downsample_ratio: 0.5


############################################
#### Camera feature triangulation parameters ####
############################################
Feature:
  # Max condition number of linear triangulation matrix accept triangulated features
  max_cond_number: 10000
  # Minimum distance to accept triangulated features
  min_dist: 0.5
  # Minimum distance to accept triangulated features
  max_dist: 5
  # Multiplier to increase/decrease lambda
  lam_mult: 10 
  # Max runs for Levenberg-Marquardt
  max_runs: 5
  # Max lambda for Levenberg-Marquardt optimization
  max_lamda: 1e10
  # Cutoff for dx increment to consider as converged
  min_dx: 1e-6
  # Cutoff for cost decrement to consider as converged
  min_dcost: 1e-6
  # Max baseline ratio to accept triangulated features
  max_baseline: 40

############################################
####        Keyframe Strategy           ####
############################################
Keyframe:
  # option 1: frame count
  frame_count: 2 
  # option 2: relative motion constraint
  frame_motion: 0.1
  # 2: 2D space constraint, for up-looking ice surface, 3: 3D space constraint
  motion_space: 2
  # option 3: minimum tracked features
  min_tracked: 50
  # option 4: ratio = tracked feature num from last keyframe / total features at current frame
  scene_ratio: 0.8
