############################################
#### Camera feature tracking parameters ####
############################################

# option: TRACK_FEATURE, TRACK_KLT, TRACK_DESCRIPTOR
TRACK:
  mode: TRACK_KLT
  num_aruco: 1024
  downsize_aruco: false
  use_stereo: false
  max_camera: 1
  cam_id: 0
  downsample_ratio: 0.5

TRACK_KLT:
  num_pts: 250
  fast_threshold: 15
  grid_x: 5
  grid_y: 3
  min_px_dist: 8
  pyram: 3


############################################
#### Camera feature triangulation parameters ####
############################################
Feature:
  # Max condition number of linear triangulation matrix accept triangulated features
  max_cond_number: 10000
  # Minimum distance to accept triangulated features
  min_dist: 0.5
  # Minimum distance to accept triangulated features
  max_dist: 5
  # Multiplier to increase/decrease lambda
  lam_mult: 10 
  # Init lambda for Levenberg-Marquardt optimization
  init_lamda: 0.001   
  # Max runs for Levenberg-Marquardt
  max_runs: 5
  # Max lambda for Levenberg-Marquardt optimization
  max_lamda: 1e10
  # Cutoff for dx increment to consider as converged
  min_dx: 1e-6
  # Cutoff for cost decrement to consider as converged
  min_dcost: 1e-6
  # Max baseline ratio to accept triangulated features
  max_baseline: 40

############################################
####        Keyframe Strategy           ####
############################################
Keyframe:
  # option 1: frame count
  frame_count: 2 

  # option 3: minimum tracked features
  min_tracked: 50
  
  #D=0.1, V_xy = 0.3, ->0.3
  #D=0.1, V_xy = 0.4, ->0.25
  adaptive_factor: 0.33
  #
  adaptive_power: 1

  # option 2: relative motion constraint
  # default: 0.1
  frame_motion: 0.1
  # 2: 2D space constraint, for up-looking ice surface, 3: 3D space constraint
  # default: 2
  motion_space: 2
  # option 4: ratio = tracked feature num from last keyframe / total features at current frame
  # default: 0.8
  scene_ratio: 0.9

############################################
####           Depth Enhancement        ####
############################################
Enhancement:
  # brief: select how many DVL pointcloud frames based on timeoffset between DVL and anchor, from small to large
  # note: if camera_rate is 15hz, slide_window is 15, DVl_rate is 4hz, 
  #       then camera_rate/slide_window = DVl_rate/matched_num
  #       this is because more matched_num DVL will not inside slide_window, then can't be interpolate pose
  matched_num: 4

  # brief: larger value descibe the z of 4 points are diverge, then some measurement is not good (e.g. multi-path)
  # default: maybe try 0.15
  standard_deviation: 0.2