##################################################################################### 
#####                                  IMU                                      #####
##################################################################################### 
IMU:
  # Default:9.81; gravity in the place your robot deployed, e.g. GLRC
  gravity: 9.80733               

  # Note: Noise density (continuous-time) from dataset from kalibr_allen
  # Default: 1.926e-04 from datasheet
  accelerometer_noise_density: 4.2e-04

  # Note: Bias random walk from kalibr_allen
  accelerometer_random_walk: 2.857e-05

  # Note: Noise density (continuous-time) from kalibr_allen
  # Default: 8.7e-05 from datasheet
  gyroscope_noise_density: 8.014e-05

  # Note: Bias random walk from kalibr_allen
  gyroscope_random_walk: 0.534e-05


##################################################################################### 
#####                                  DVL                                      #####
##################################################################################### 
DVL:
  # imu is reference frame
  T_I_D: 
  - [  -0.999928,   0.0116206, -0.00288846,   0.433828]
  - [  0.0115923,    0.999886,  0.00962664,   0.086180]
  - [      0.003,  0.00959246,   -0.999949,  -0.302024]
  - [        0.0,         0.0,         0.0,        1.0]
  # Default:0.0; Time offset from Temporal calibrtion between DVL and IMU: (t_imu = t_dvl + t_offset)
  # TODO: this value will be overide by IMU-DVL alignment
  timeoffset_I_D: 0.0         
  # Default:1.0; Scale factor for DVL measurement effected by sound speed (caused by salinity, temperature...)
  scale: 0.944666667
  # noise on DVL tottom track 3-axis velocity measurement
  noise_bt: [0.1, 0.1, 0.2]


##################################################################################### 
#####                               Pressure                                    #####
##################################################################################### 
PRESSURE:
  # Note: the angle that the actual mounting position rotate to the standing position,
  #       used to transfer pressure measurement into DVL frame's Z
  # Default: 0: x-forward, up-looking; PI: x-forward, down-looking; -PI/2: x-forward, right-looking; PI/2: x-forward, left-looking
  mount_angle: 0
  # noise for pressure update
  # default: 0.01
  noise_pressure: 0.1


##################################################################################### 
#####                                 CAM0                                      #####
##################################################################################### 
CAM0:
  T_C_I:
  - [0.00786236726823823,    0.9999532121420647,    0.0056353090162310805, -0.1232206727449017]
  - [0.9999681294260654,    -0.00785441912633285,  -0.0014311646745676972, -0.310185995908388]
  - [-0.0013868356345183388, 0.005646381757991208, -0.9999830973871349,    -0.27812151547998104]
  - [0.0,                    0.0,                   0.0,                    1.0]
  ## Alaska matlab: radial-tangential[k1,k2,k1,k2]
  # distortion_coeffs: [-0.229971614369661,0.173683036312323,-7.457584765784308e-04,0.002259672821916]
  ## Alaska matlab: f_x, f_y, c_x, c_y
  # intrinsics: [1845.542490218492,1846.046949112978,825.6913274592704,605.8504151895138] 

  ## GLRC kalib: radial-tangential[k1,k2,k1,k2]
  # distortion_coeffs: [0.23117413334281256, 0.14158516202577756, -0.0003020869226409155, 0.0016221154832216692]
  ## GLRC matlab: f_x, f_y, c_x, c_y
  # intrinsics: [1832.8127123808745, 1831.3023458914286, 818.6226797023049, 614.5433318640432]  

  ## metashape: radial-tangential[k1,k2,p1,p1,k3]
  distortion_coeffs: [-2.37387184652287003e-01, 2.18272742543289017e-01, -3.44046297220564870e-05, 1.05398436356655815e-03, -1.55006764704936351e-01]
  ## metashape: f_x, f_y, c_x, c_y
  intrinsics: [1836.16899521511550, 1836.16899521511550, 815.603781369907551, 614.213209479135003]  

  resolution: [1616, 1240]
  # Default:-0.09398272330912658, from kalibr
  timeoffset_C_I: 0
  camera_model: pinhole
  distortion_model: radtan
  # unit in pixel
  noise: 0.01
  # 
  rostopic: /rov_remote/sensors/stereo/left/image_decompressed

# CAM1:
#   T_C_I: