##### System Parameters #####
SYS:
  # Default: ; 
  # Note: frequency for backend processing(MSCKF update), increase if more data need for processing 
  backend_hz: 100
  # Default: 2.0
  # Note: use this simply filter bad DVL velocity measurement
  dvl_v_threshold: 2.0 

####################################################################################
#####################    System Initailization Configuration    ####################
####################################################################################

INIT:
  # Default: 1; (0: static; 1:DVL-aided; 2:SFM-aided)
  # Note: Estimate IMU bias and find out the rotation matrix between inertial world frame and IMU body frame;
  imu_init_mode: 1      

  # Default: 10
  # Note: how many IMU data is selected to detect IMU jump (suddenly move)  
  imu_window: 10

  # Default: 0.2
  # Note: the IMU variance threshold that indicates IMU jump inclued
  imu_var: 0.2

  # Default: 0.07
  # Note: IMU accleraion difference in x-axis(forward direction) shows at the suddenly movement time
  imu_delta: 0.07

  # Default: 5
  # Note: how many DVL data is selected to detect DVL jump (suddenly move)  
  dvl_window: 4
  
  # Default: 0.05
  # Note: DVL velocity difference in x-axis(forward direction) shows at the suddenly movement time
  dvl_delta: 0.05

  # Default: 1s
  #Note: how many second selected for initialization
  dvl_init_duration: 1

  # use the given initialized state or not
  init_state_given: false

  # example: t, qx,qy,qz,qw, px,py,pz, vx,vy,vz, bgx,bgy,bgz, bax,bay,baz
  init_state: [0, 0,0,0,0, 0,0,0, 0,0,0, 0,0,0, 0,0,0]
  
####################################################################################
############################    MSCKF estimation setup    ##########################
####################################################################################

MSCKF:
  ##################################    DVL    ###################################

  # enable DVL exterisic rotation calibration 
  dvl_exterisic_R: false
  # enable DVL exterisic translation calibration 
  dvl_exterisic_p: false
  # enable DVL time offset calibration
  dvl_timeoffset: false
  # enable DVL scale calibration
  dvl_scale: false
  # Max DVL clone 
  dvl_clone: 0 

  ################################    Camera    ##################################

  # enable camera exterisic rotation calibration 
  cam_exterisic_R: false
  # enable camera exterisic translation calibration 
  cam_exterisic_p: false
  # enable camera time offset calibration
  cam_timeoffset: false
  # Max camera clone
  cam_clone: 11 

  ################################    Update    ##################################

  # in open_vins(40), but it's occasionally update at 40
  # but here, tracking will stop so always update as 40
  max_msckf_update: 20